events {}
http {
    server {
        listen 80;
        server_name pujasewa.com.np;
        return 301 https://$server_name$request_uri;
    }
    server {
        listen 443 ssl;
        server_name pujasewa.com.np;
        ssl_certificate /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/privkey.pem;
        location / {
            proxy_pass http://frontend:5173;
            proxy_set_header Host $host;
        }
        location /api {
            proxy_pass http://backend:3000;
            proxy_set_header Host $host;
        }
    }
}
